### PR TITLE
manage.py updatedatabase Command

### PR DESCRIPTION
**Pull request by cweems**
Added an a manage.py command `updatedatabase` that will:
1. Create a database backup in heroku
2. Download the file locally
3. Import the dump file
4. Delete the dump file.

Usage: `python manage.py updatedatabase`.

I think this will be useful for having an accurate representation of our content locally. @millzpaugh and @glassresistor thoughts on this? Getting back into the swing of things with Python after several months so feel free to let me know if there's anything blatantly dumb here.

### CODE REVIEW

**Comment by millzpaugh** [comment]
This is awesome!!! A few things - 

1) Python 3 takes raw_input instead of input so I changed that for the command line prompt. 

2) Since CfA has so many apps on heroku, the heroku commands needed to specify the app. 

3) I added an error output if an admin says n or the script doesn't happen to run successfully.

**Comment by cweems** [comment]
@millzpaugh awesome! One thing I've encountered already is that because this blows the entire database away, you'll need a new superuser. Probably the best thing is to just have a super user account in production and use those credentials.

**Comment by cweems** [comment]
@millzpaugh although actually I think `raw_input` is for Python 2 and `input` is what's used now: http://stackoverflow.com/questions/4915361/whats-the-difference-between-raw-input-and-input-in-python3-x

**Comment by millzpaugh** [comment]
Yes - you were right! My terminal is pointing to the mac python 2.7 path...oops!

**Comment by millzpaugh** [comment]
This seems to be dumping all the step pages, but for some reason those pages aren't getting created as wagtail pages and therefore aren't displaying in the Wagtail interface.

**Comment by cweems** [comment]
Closing this as I think we're going to be doing this with fixtures instead.

**Pull request closed without merging**
