### PR TITLE
Setup admin user on postinstall

### LINKED ISSUE #20: Set up Fixtures for Dev Database

### PR DESCRIPTION
**Pull request by cweems**
Sets up an admin user for review apps after the app is deployed. Admin username is admin, and the password is in our heroku settings.

Going to say this closes #20 for now, although setting up starter data will be an ongoing task.

### CODE REVIEW

**Comment by millzpaugh** [comment]
I was getting an error running tests locally - I changed it so factories.py gets the TEST_ADMIN_PASSWORD from the django conf settings and I added that variable to the local settings example.

**Review by millzpaugh — CHANGES_REQUESTED** [review]
I was getting an error running tests locally - I changed factories.py to get the TEST_ADMIN_PASSWORD from the django conf settings and I added that variable to the local settings example. For some reason, Heroku doesn't seem to be registering the TEST_ADMIN_PASSWORD environment variable now. I think the project should be setup so we can run tests without errors in all environments. @glassresistor Could you look at this since you're most familiar with the settings configuration?

We should also be using the Django logging system for STOUDT - I'm going to create a branch and work on that this afternoon so let's not worry about changing that in this branch. 

Otherwise this looks great!

**Comment by glassresistor** [comment]
I made another PR and merge in your changes

**Review by glassresistor — COMMENTED** [review]
changes were good so i squashed and merged

**Pull request closed without merging**
